version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "buildSystem/dependencies.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Accept Licenses
          # Captures SIGPIPE 141 error but still allow repeating "y" to accept all licenses
          command: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - run:
          name: Add google-services.json
          command: echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json
      - run:
          name: Run Lint Tests
          command: ./gradlew ktlintCheck  --build-cache --stacktrace
      - run:
          name: Build project & run all tests
          command: ./gradlew build --build-cache --stacktrace
      - run:
          name: Generate Debug APK
          command: ./gradlew assembleDebug --build-cache --stacktrace
      - store_artifacts:
          path: ./app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "buildSystem/dependencies.gradle" }}
