package edu.nitt.deltaapp.core.storage

object FestDbUtils {

  const val DATABASE_VERSION = 1
  const val DATABASE_NAME = "FestDB"

  const val TABLE_ABOUT_US = "AboutUs"
  const val TABLE_CLUSTERS = "Clusters"
  const val TABLE_GALLERY = "Gallery"
  const val TABLE_GUEST_LECTURES = "GuestLectures"
  const val TABLE_HOSPITALITY = "Hospitality"
  const val TABLE_INFORMALS = "Informals"
  const val TABLE_SPONSORS = "Sponsors"
  const val TABLE_WORKSHOPS = "Workshops"
  const val TABLE_SCHEDULE = "Schedule"

  const val KEY_ID = "id"
  const val KEY_NAME = "name"
  const val KEY_START_TIME = "startTime"
  const val KEY_END_TIME = "endTime"
  const val KEY_VENUE = "venue"
  const val KEY_DESCRIPTION = "description"
  const val KEY_LAST_UPDATE_TIME = "lastUpdateTime"
  const val KEY_LOCATION_X = "locationX"
  const val KEY_LOCATION_Y = "locationY"
  const val KEY_MAX_LIMIT = "maxLimit"
  const val KEY_CLUSTER = "cluster"
  const val KEY_DATE = "date"
  const val KEY_REGISTERED = "registered"
  const val KEY_CONTACT = "contact"
  const val KEY_IMAGE = "image"
  const val KEY_DAY = "day"
  const val KEY_REGISTRATAION_LINK = "registrationLink"
  const val KEY_INSTRUCTION = "instruction"
  const val KEY_HOW_TO_REACH = "howToReach"
  const val KEY_ACCOMODATION = "accomodation"
  const val KEY_CONTACTS = "contacts"
  const val KEY_FAQS = "faqs"
  const val KEY_EVENT_INFO = "eventInfo"
  const val KEY_TESTIMONIALS = "testimonials"
  const val KEY_FILENAME = "filename"
  const val KEY_MIME_TYPE = "mimeType"
  const val KEY_FILESIZE = "filesize"
  const val KEY_WIDTH = "width"
  const val KEY_HEIGHT = "height"
  const val KEY_SIZES = "sizes"
  const val KEY_URL = "url"
  const val KEY_CLUSTER_ID = "clusterID"
  const val KEY_TYPE = "type"
}
