name: Fest CI

on:
  push:
    paths:
      - '**.kt'
      - '**.java'
      - '**.gradle'
      - '**.yml'

    branches:
      - "master"
      - "dev*"
      - "festember*"
      - "nittfest*"
      - "pragyan*"

  pull_request:
    branches:
      - "**"

jobs:
  check:
    name: Check Commit
    runs-on: ubuntu-18.04

    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check Commit
        uses: adityaa30/check-commit@master

  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 30

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v1
        env:
          cache-name: cache-files
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('~/.gradle/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}-

      - name: Unit tests
        run: bash ./gradlew test --build-cache --stacktrace

  lint:
    name: Lint Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 30

      - name: ktlintCheck
        run: ./gradlew ktlintCheck

